export const country = [
  { value: "ae", label: "Birleşik Arap Emirlikleri" },
  { value: "ar", label: "Arjantin" },
  { value: "at", label: "Avusturya" },
  { value: "au", label: "Avustralya" },
  { value: "be", label: "Belçika" },
  { value: "bg", label: "Bulgaristan" },
  { value: "br", label: "Brezilya" },
  { value: "ca", label: "Kanada" },
  { value: "ch", label: "İsviçre" },
  { value: "cn", label: "Çin" },
  { value: "co", label: "Kolombiya" },
  { value: "cu", label: "Küba" },
  { value: "cz", label: "Çekya" },
  { value: "de", label: "Almanya" },
  { value: "eg", label: "Mısır" },
  { value: "fr", label: "Fransa" },
  { value: "gb", label: "Birleşik Krallık" },
  { value: "gr", label: "Yunanistan" },
  { value: "hk", label: "Hong Kong" },
  { value: "hu", label: "Macaristan" },
  { value: "id", label: "Endonezya" },
  { value: "ie", label: "İrlanda" },
  { value: "il", label: "İsrail" },
  { value: "in", label: "Hindistan" },
  { value: "it", label: "İtalya" },
  { value: "jp", label: "Japonya" },
  { value: "kr", label: "Güney Kore" },
  { value: "lt", label: "Litvanya" },
  { value: "lv", label: "Letonya" },
  { value: "ma", label: "Fas" },
  { value: "mx", label: "Meksika" },
  { value: "my", label: "Malezya" },
  { value: "ng", label: "Nijerya" },
  { value: "nl", label: "Hollanda" },
  { value: "no", label: "Norveç" },
  { value: "nz", label: "Yeni Zelanda" },
  { value: "ph", label: "Filipinler" },
  { value: "pl", label: "Polonya" },
  { value: "pt", label: "Portekiz" },
  { value: "ro", label: "Romanya" },
  { value: "rs", label: "Sırbistan" },
  { value: "ru", label: "Rusya" },
  { value: "sa", label: "Suudi Arabistan" },
  { value: "se", label: "İsveç" },
  { value: "sg", label: "Singapur" },
  { value: "si", label: "Slovenya" },
  { value: "sk", label: "Slovakya" },
  { value: "th", label: "Tayland" },
  { value: "tr", label: "Türkiye" },
  { value: "tw", label: "Tayvan" },
  { value: "ua", label: "Ukrayna" },
  { value: "us", label: "Amerika Birleşik Devletleri" },
  { value: "ve", label: "Venezuela" },
  { value: "za", label: "Güney Afrika" },
];


export const settings = {
  dots: false,
  infinite: true,
  slidesToShow: 2,
  slidesToScroll: 1,
  autoplay: true,
  autoplaySpeed: 2500,
};


